# Generated by Django 5.2.16 on 2026-08-11 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField(help_text='Penalty amount in Indian rupees')),
                ('days_overdue', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('waived', 'Waived')], default='unpaid', max_length=10)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('book_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties', to='catalog.bookinstance')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-assessed_at',),
            },
        ),
    ]
