# Generated by Django 5.2.16 on 2026-08-11 15:28

import datetime

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_loans(apps, schema_editor):
    BookInstance = apps.get_model('catalog', 'BookInstance')
    Loan = apps.get_model('catalog', 'Loan')
    Penalty = apps.get_model('catalog', 'Penalty')

    for instance in BookInstance.objects.filter(
        status='o',
        borrower__isnull=False,
        due_back__isnull=False,
    ).select_related('book'):
        issued_date = instance.due_back - datetime.timedelta(days=15)
        Loan.objects.get_or_create(
            book_instance=instance,
            status='active',
            defaults={
                'borrower_id': instance.borrower_id,
                'book_title': instance.book.title,
                'issued_at': datetime.datetime.combine(
                    issued_date,
                    datetime.time.min,
                    tzinfo=datetime.timezone.utc,
                ),
                'due_date': instance.due_back,
            },
        )

    for penalty in Penalty.objects.filter(loan__isnull=True):
        returned_at = penalty.assessed_at
        due_date = returned_at.date() - datetime.timedelta(days=penalty.days_overdue)
        issued_date = due_date - datetime.timedelta(days=15)
        loan = Loan.objects.create(
            borrower_id=penalty.borrower_id,
            book_instance_id=penalty.book_instance_id,
            book_title=penalty.book_title,
            issued_at=datetime.datetime.combine(
                issued_date,
                datetime.time.min,
                tzinfo=datetime.timezone.utc,
            ),
            due_date=due_date,
            returned_at=returned_at,
            status='returned',
        )
        penalty.loan_id = loan.pk
        penalty.save(update_fields=['loan'])


def reverse_backfill(apps, schema_editor):
    Penalty = apps.get_model('catalog', 'Penalty')
    Loan = apps.get_model('catalog', 'Loan')
    Penalty.objects.update(loan=None)
    Loan.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_penalty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('returned', 'Returned'), ('lost', 'Lost')], default='active', max_length=10)),
                ('renewal_count', models.PositiveSmallIntegerField(default=0)),
                ('book_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='catalog.bookinstance')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_issued', to=settings.AUTH_USER_MODEL)),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_returned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-issued_at',),
            },
        ),
        migrations.AddField(
            model_name='penalty',
            name='loan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalty', to='catalog.loan'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='catalog.book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.RunPython(backfill_loans, reverse_backfill),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('book_instance',), name='one_active_loan_per_copy'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('book', 'borrower'), name='one_active_reservation_per_book_member'),
        ),
    ]
