# Generated by Django 5.2.16 on 2026-08-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_scanaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_url',
            field=models.URLField(blank=True, max_length=700),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo_url',
            field=models.URLField(blank=True, max_length=700),
        ),
    ]
