# Generated by Django 5.2.16 on 2026-08-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_book_cover_url_profile_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='accession_number',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='condition_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='shelf_location',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved'), ('l', 'Lost')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
