# Generated by Django 5.2.16 on 2026-08-12 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def protect_postgrest_table(apps, schema_editor):
    """Keep this internal Django table inaccessible through PostgREST."""
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute('ALTER TABLE public.catalog_penaltytransaction ENABLE ROW LEVEL SECURITY')
            cursor.execute('REVOKE ALL ON TABLE public.catalog_penaltytransaction FROM anon, authenticated')


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_bookinstance_accession_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(choices=[('paid', 'Paid'), ('waived', 'Waived')], max_length=10)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('bank', 'Bank transfer'), ('waiver', 'Waiver')], max_length=10)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('penalty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='catalog.penalty')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.RunPython(protect_postgrest_table, migrations.RunPython.noop),
    ]
