import csv
import uuid
from pathlib import Path

from django.contrib.auth.models import User
from django.core.management.base import BaseCommand, CommandError
from django.db import transaction

from catalog.models import Author, Book, BookInstance, Genre
from catalog.permissions import LEGACY_ROLE_MAP, STUDENT, sync_user_role


class Command(BaseCommand):
    help = 'Import CSV files generated by export_library_data (safe to rerun).'

    def add_arguments(self, parser):
        parser.add_argument('directory', help='Directory containing books.csv, copies.csv, members.csv')
        parser.add_argument('--dry-run', action='store_true')

    @transaction.atomic
    def handle(self, *args, **options):
        source = Path(options['directory']).resolve()
        if not source.is_dir():
            raise CommandError(f'Directory does not exist: {source}')
        counts = {'books': 0, 'copies': 0, 'members': 0}
        if (source / 'books.csv').exists():
            for row in self._rows(source / 'books.csv'):
                author, _ = Author.objects.get_or_create(first_name=row['author_first_name'], last_name=row['author_last_name'])
                book, _ = Book.objects.update_or_create(isbn=row['isbn'], defaults={'title': row['title'], 'author': author, 'summary': row['summary'], 'cover_url': row.get('cover_url', '')})
                book.genre.set(Genre.objects.get_or_create(name=name.strip())[0] for name in row.get('genres', '').split('|') if name.strip())
                counts['books'] += 1
        if (source / 'members.csv').exists():
            for row in self._rows(source / 'members.csv'):
                user, created = User.objects.update_or_create(username=row['username'], defaults={'first_name': row['first_name'], 'last_name': row['last_name'], 'email': row['email'], 'is_active': row.get('is_active', 'True').lower() in {'true', '1', 'yes'}})
                if created:
                    user.set_unusable_password(); user.save(update_fields=['password'])
                source_role = row.get('role', STUDENT)
                role = LEGACY_ROLE_MAP.get(source_role, source_role)
                valid_roles = {choice[0] for choice in user.profile.ROLE_CHOICES}
                user.profile.role = role if role in valid_roles else STUDENT
                user.profile.save(update_fields=['role'])
                sync_user_role(user, user.profile.role)
                counts['members'] += 1
        if (source / 'copies.csv').exists():
            for row in self._rows(source / 'copies.csv'):
                lookup = {'accession_number': row['accession_number']} if row['accession_number'] else {'pk': uuid.UUID(row['id'])}
                BookInstance.objects.update_or_create(**lookup, defaults={'book': Book.objects.get(isbn=row['isbn']), 'accession_number': row['accession_number'] or None, 'imprint': row['imprint'], 'shelf_location': row.get('shelf_location', ''), 'status': row.get('status', 'a'), 'condition_notes': row.get('condition_notes', '')})
                counts['copies'] += 1
        if options['dry_run']:
            transaction.set_rollback(True)
        suffix = ' (dry run; rolled back)' if options['dry_run'] else ''
        self.stdout.write(self.style.SUCCESS(f"Imported {counts['books']} books, {counts['copies']} copies, {counts['members']} members{suffix}"))

    @staticmethod
    def _rows(path):
        with path.open(encoding='utf-8-sig', newline='') as stream:
            yield from csv.DictReader(stream)
